<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.mPg_grJ.Symfony\Component\Form\FormBuilderInterface' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormConfigInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormConfigBuilderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/FormBuilderInterface.php';

return $this->privates['.errored..service_locator.mPg_grJ.Symfony\\Component\\Form\\FormBuilderInterface'] = new \Symfony\Component\Form\FormBuilderInterface();
