<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfCJfq7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfCJfq7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVfCJfq7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVfCJfq7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVfCJfq7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VfCJfq7',
    'container.build_id' => '1ee24847',
    'container.build_time' => 1561568953,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfCJfq7');
