<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTDfBcrF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTDfBcrF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTDfBcrF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTDfBcrF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTDfBcrF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TDfBcrF',
    'container.build_id' => '873cc98e',
    'container.build_time' => 1563131866,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTDfBcrF');
