<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfheqpJ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfheqpJ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVfheqpJ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVfheqpJ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVfheqpJ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VfheqpJ',
    'container.build_id' => '4d270026',
    'container.build_time' => 1558965674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfheqpJ');
